# frozen_string_literal: true

plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'

# Style
Style/Documentation:
  Enabled: false  # Can be enabled later for public APIs

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

# Metrics
Metrics/ClassLength:
  Max: 300  # CLI class growing with new commands

Metrics/MethodLength:
  Max: 60  # Allow slightly longer methods for command handlers
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'

Metrics/AbcSize:
  Max: 40  # Allow higher complexity for command handlers

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 12

# Layout
Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\A\s*#'  # Allow long comments

# Naming
Naming/VariableNumber:
  Enabled: false

# RSpec
RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

# Security
Security/Eval:
  Enabled: true

Security/Open:
  Enabled: true
